### ISSUE TITLE
How to plot graph from metrics api URL

### ISSUE THREAD

**Issue by rahulpathak109** [u39kun/ambari-grafana#2]
Hi,

I have following url.

http://ambari-server:8080/api/v1/clusters/hdp23/hosts/hostname-of-regionserver/host_components/HBASE_REGIONSERVER

How can I plot this on Grafana?

**Comment by u39kun** [comment]
Hi @rahulpathak109 

https://github.com/u39kun/ambari-grafana/pull/1, once merged, should let you do just that.

**Comment by u39kun** [comment]
I've merged PR #1 and updated ambari-grafana.tgz.
Please deploy ambari-grafana.tgz on your cluster again and give it a try.  You should be able to specify the hostname in the query editor now.  If you omit the hostname, the selected metric for all the instances of the selected component will be aggregated across all hosts.

**Comment by rahulpathak109** [comment]
Thanks.

I am able to see hostname now, but component name field is not auto populating.

**Comment by u39kun** [comment]
Component auto populates fine for me with the new code.
Can you try clearing the cache on your browser and try again?
If you still have issues, let me know.

**Comment by rahulpathak109** [comment]
You were right. Browser problem.

Thanks again. :)

**Comment by u39kun** [comment]
Cool, glad it worked for you.
